### PR TITLE
added docker compose container run feature

### PR DESCRIPTION
**Pull request by telostia**
**Note**
- currently assumes the binary of robonomics to exist in the /target/release to be able to work.

### CODE REVIEW

**Comment by akru** [comment]
That looks very good! Thank you @telostia 

So, I want to make automated builds on docker hub, currently, it uses precompiled binary, I agree that it's a good approach, but maybe we can use it from CI, for example?

**Comment by telostia** [comment]
You mean like these commands? https://github.com/telostia/robonomics-docker.git

It's a set of build scripts to login, run, pull and deploy the docker image?

**Comment by akru** [comment]
@telostia I've made docker hub repository https://hub.docker.com/repository/docker/robonomics/robonomics but automated builds are failed, let's make it successful. What do you think?

**Comment by telostia** [comment]
sure, what steps did you take to run it?, it just needs to auto login into docker to push it to docker hub first

**Comment by akru** [comment]
I've to use the Automated Builds feature (https://docs.docker.com/docker-hub/builds/), which needs to set the Dockerfile only for automated tracking of the changes (commits) in the repo and build the latest and tagged images.

**Comment by telostia** [comment]
Is this for release builds or development builds? you want to build from source?

**Comment by akru** [comment]
Technically, the binary built from the source at CI (https://github.com/airalab/robonomics/actions/runs/218605335) and docker builders can use this artifact as well. Probably, we also can use hooks to let docker builders known that CI builds finished.

Another way is directly pushing into docker from CI as the final step of building, it also works IMO.

**Comment by telostia** [comment]
Ok, did you try to build it manually? if that works then location of binary should work(assuming its in /target/release. If the binary you built is not in that location then the solution is obvious, theres 2 ways, you either make another script called autobuild-docker.sh and refer to that binary location or we make one from scratch. Which do you prefer? this build file was mainly for end users to build and run using compose after they build it themselves, others might just pull from docker.hub and run it .

**Comment by akru** [comment]
As you can see here: https://github.com/airalab/robonomics/blob/master/.github/workflows/integration.yml#L32 the binary is already build & ready from GitHub Actions. Let's use it for Docker build. What do you think? Probably we can add just a two additional steps into CI:
1. docker build
2. docker push

In that case, CI will automatically build the binary and use it for artifacts and for docker images.

**Comment by telostia** [comment]
that looks like its located at target/release/robonomics, where is your project located at? i accidently made the assumption that project is located at /root/robonomics, i'll change it back to relative from exact location.

**Pull request merged**
